---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/admins/sign_in":
    post:
      summary: Admin Sign in
      tags:
      - Admin Authentication
      parameters: []
      responses:
        '200':
          description: successful sign in
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                admin:
                  type: object
                  properties:
                    email:
                      type: string
                      example: admin@admin.com
                    password:
                      type: string
                      example: admin123
                  required:
                  - email
                  - password
  "/admins/sign_out":
    delete:
      summary: Admin Sign out
      tags:
      - Admin Authentication
      responses:
        '204':
          description: successful sign out
  "/books":
    get:
      summary: Retrieves all books, optionally filtered by genre
      tags:
      - Books
      description: Retrieves a list of all books. Optionally, you can filter by genre.
      parameters:
      - name: genre
        in: query
        description: Filter books by genre
        schema:
          type: string
      responses:
        '200':
          description: Books found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    author:
                      type: string
                    genre:
                      type: string
                    isbn:
                      type: string
                    available_copies:
                      type: integer
                  required:
                  - id
                  - title
                  - author
                  - genre
                  - isbn
                  - available_copies
  "/users":
    post:
      summary: Signs up a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: newuser@example.com
                    password:
                      type: string
                      example: password123
                  required:
                  - email
                  - password
                  - password_confirmation
              required:
              - user
  "/users/sign_in":
    post:
      summary: Signs in a user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user signed in
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: user@example.com
                    password:
                      type: string
                      example: password123
                  required:
                  - email
                  - password
              required:
              - user
  "/users/sign_out":
    delete:
      summary: Signs out a user
      tags:
      - Users
      responses:
        '204':
          description: user signed out
  "/users/me":
    get:
      summary: Retrieves current user details
      tags:
      - Users
      responses:
        '200':
          description: user details
        '401':
          description: unauthorized
servers:
- url: http://127.0.0.1:3000/
  variables:
    defaultHost:
      default: http://127.0.0.1:3000/
