---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/books":
    get:
      summary: Retrieves all books, optionally filtered by genre
      tags:
      - Books
      description: Retrieves a list of all books. Optionally, you can filter by genre.
      parameters:
      - name: genre
        in: query
        description: Filter books by genre
        schema:
          type: string
      responses:
        '200':
          description: Books found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    author:
                      type: string
                    genre:
                      type: string
                    isbn:
                      type: string
                    available_copies:
                      type: integer
                  required:
                  - id
                  - title
                  - author
                  - genre
                  - isbn
                  - available_copies
servers:
- url: http://127.0.0.1:3000/
  variables:
    defaultHost:
      default: http://127.0.0.1:3000/
