---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/admins/sign_in":
    get:
      summary: Admin Sign in page
      tags:
      - Admin Authentication
      responses:
        '200':
          description: sign in page
    post:
      summary: Admin Sign in
      tags:
      - Admin Authentication
      parameters: []
      responses:
        '200':
          description: successful sign in
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: admin@admin.com
                password:
                  type: string
                  example: admin123
              required:
              - email
              - password
  "/admins/sign_out":
    delete:
      summary: Admin Sign out
      tags:
      - Admin Authentication
      responses:
        '204':
          description: successful sign out
  "/admins/password/new":
    get:
      summary: New password reset page
      tags:
      - Admin Authentication
      responses:
        '200':
          description: password reset page
  "/admins/password/edit":
    get:
      summary: Edit password page
      tags:
      - Admin Authentication
      responses:
        '200':
          description: edit password page
  "/admins/password":
    post:
      summary: Send reset password instructions
      tags:
      - Admin Authentication
      parameters: []
      responses:
        '200':
          description: password reset email sent
        '404':
          description: email not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: admin@admin.com
              required:
              - email
    patch:
      summary: Update password
      tags:
      - Admin Authentication
      parameters: []
      responses:
        '200':
          description: password updated
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reset_password_token:
                  type: string
                  example: reset-token
                password:
                  type: string
                  example: newpassword
                password_confirmation:
                  type: string
                  example: newpassword
              required:
              - reset_password_token
              - password
              - password_confirmation
    put:
      summary: Update password
      tags:
      - Admin Authentication
      parameters: []
      responses:
        '200':
          description: password updated
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reset_password_token:
                  type: string
                  example: reset-token
                password:
                  type: string
                  example: newpassword
                password_confirmation:
                  type: string
                  example: newpassword
              required:
              - reset_password_token
              - password
              - password_confirmation
  "/admins/sign_up":
    get:
      summary: New registration page
      tags:
      - Admin Authentication
      responses:
        '200':
          description: registration page
    post:
      summary: Create admin
      tags:
      - Admin Authentication
      parameters: []
      responses:
        '201':
          description: successful registration
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: newadmin@admin.com
                password:
                  type: string
                  example: password
                password_confirmation:
                  type: string
                  example: password
              required:
              - email
              - password
              - password_confirmation
  "/admins/cancel":
    get:
      summary: Cancel registration page
      tags:
      - Admin Authentication
      responses:
        '200':
          description: cancel registration page
  "/admins/edit":
    get:
      summary: Edit registration page
      tags:
      - Admin Authentication
      responses:
        '200':
          description: edit registration page
    patch:
      summary: Update admin
      tags:
      - Admin Authentication
      parameters: []
      responses:
        '200':
          description: admin updated
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: updatedadmin@example.com
                password:
                  type: string
                  example: newpassword
                password_confirmation:
                  type: string
                  example: newpassword
              required:
              - email
              - password
              - password_confirmation
    put:
      summary: Update admin
      tags:
      - Admin Authentication
      parameters: []
      responses:
        '200':
          description: admin updated
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: updatedadmin@example.com
                password:
                  type: string
                  example: newpassword
                password_confirmation:
                  type: string
                  example: newpassword
              required:
              - email
              - password
              - password_confirmation
    delete:
      summary: Delete admin
      tags:
      - Admin Authentication
      responses:
        '204':
          description: admin deleted
  "/books":
    get:
      summary: Retrieves all books, optionally filtered by genre
      tags:
      - Books
      description: Retrieves a list of all books. Optionally, you can filter by genre.
      parameters:
      - name: genre
        in: query
        description: Filter books by genre
        schema:
          type: string
      responses:
        '200':
          description: Books found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    author:
                      type: string
                    genre:
                      type: string
                    isbn:
                      type: string
                    available_copies:
                      type: integer
                  required:
                  - id
                  - title
                  - author
                  - genre
                  - isbn
                  - available_copies
    post:
      summary: Creates a new book
      tags:
      - Books
      description: Creates a new book entry.
      parameters: []
      responses:
        '201':
          description: Book created
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: The Great Gatsby
                author:
                  type: string
                  example: F. Scott Fitzgerald
                genre:
                  type: string
                  example: Novel
                isbn:
                  type: string
                  example: '9780743273565'
                available_copies:
                  type: integer
                  example: 10
              required:
              - title
              - author
              - genre
              - isbn
              - available_copies
  "/books/{id}":
    parameters:
    - name: id
      in: path
      description: ID of the book
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves a specific book
      tags:
      - Books
      description: Retrieves a specific book by its ID.
      responses:
        '200':
          description: Book found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  author:
                    type: string
                  genre:
                    type: string
                  isbn:
                    type: string
                  available_copies:
                    type: integer
                required:
                - id
                - title
                - author
                - genre
                - isbn
                - available_copies
        '404':
          description: Book not found
    patch:
      summary: Updates a specific book
      tags:
      - Books
      description: Updates a specific book by its ID.
      parameters: []
      responses:
        '200':
          description: Book updated
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: The Great Gatsby Updated
                author:
                  type: string
                  example: F. Scott Fitzgerald
                genre:
                  type: string
                  example: Novel
                isbn:
                  type: string
                  example: '9780743273565'
                available_copies:
                  type: integer
                  example: 15
              required:
              - title
              - author
              - genre
              - isbn
              - available_copies
    delete:
      summary: Deletes a specific book
      tags:
      - Books
      description: Deletes a specific book by its ID.
      responses:
        '204':
          description: Book deleted
        '404':
          description: Book not found
  "/users/sign_in":
    get:
      summary: User Sign in page
      tags:
      - User Authentication
      responses:
        '200':
          description: sign in page
    post:
      summary: User Sign in
      tags:
      - User Authentication
      parameters: []
      responses:
        '200':
          description: successful sign in
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: password
              required:
              - email
              - password
  "/users/sign_out":
    delete:
      summary: User Sign out
      tags:
      - User Authentication
      responses:
        '204':
          description: successful sign out
  "/users/password/new":
    get:
      summary: New password reset page
      tags:
      - User Authentication
      responses:
        '200':
          description: password reset page
  "/users/password/edit":
    get:
      summary: Edit password page
      tags:
      - User Authentication
      responses:
        '200':
          description: edit password page
  "/users/password":
    post:
      summary: Send reset password instructions
      tags:
      - User Authentication
      parameters: []
      responses:
        '200':
          description: password reset email sent
        '404':
          description: email not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
              required:
              - email
    patch:
      summary: Update password
      tags:
      - User Authentication
      parameters: []
      responses:
        '200':
          description: password updated
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reset_password_token:
                  type: string
                  example: reset-token
                password:
                  type: string
                  example: newpassword
                password_confirmation:
                  type: string
                  example: newpassword
              required:
              - reset_password_token
              - password
              - password_confirmation
    put:
      summary: Update password
      tags:
      - User Authentication
      parameters: []
      responses:
        '200':
          description: password updated
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reset_password_token:
                  type: string
                  example: reset-token
                password:
                  type: string
                  example: newpassword
                password_confirmation:
                  type: string
                  example: newpassword
              required:
              - reset_password_token
              - password
              - password_confirmation
  "/users/sign_up":
    get:
      summary: New registration page
      tags:
      - User Authentication
      responses:
        '200':
          description: registration page
    post:
      summary: Create user
      tags:
      - User Authentication
      parameters: []
      responses:
        '201':
          description: successful registration
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: newuser@example.com
                password:
                  type: string
                  example: password
                password_confirmation:
                  type: string
                  example: password
              required:
              - email
              - password
              - password_confirmation
  "/users/cancel":
    get:
      summary: Cancel registration page
      tags:
      - User Authentication
      responses:
        '200':
          description: cancel registration page
  "/users/edit":
    get:
      summary: Edit registration page
      tags:
      - User Authentication
      responses:
        '200':
          description: edit registration page
    patch:
      summary: Update user
      tags:
      - User Authentication
      parameters: []
      responses:
        '200':
          description: user updated
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: updateduser@example.com
                password:
                  type: string
                  example: newpassword
                password_confirmation:
                  type: string
                  example: newpassword
              required:
              - email
              - password
              - password_confirmation
    delete:
      summary: Delete user
      tags:
      - User Authentication
      responses:
        '204':
          description: user deleted
servers:
- url: http://127.0.0.1:3000/
  variables:
    defaultHost:
      default: http://127.0.0.1:3000/
